### PR TITLE
typos fixed and proposals

### PR DESCRIPTION
**Pull request by pmoule**
### Fixes
- fixed some typos
### Proposals for discussion
- 3.2.2: It's a bit unclear how to handle multiple items. From my understanding exactly one key MUST be named "default".
- 6.: links in HAL responses should contain type application/prs.hal-forms+json. There should be some indication about which media type to expect as response.

### CODE REVIEW

**Review by mamund — COMMENTED** [review]
Can you explain a bit more why you think the change in text for the "if there is only" -> "for exactly..." is important?

**Review by mamund — CHANGES_REQUESTED** [review]
for the `rel` and `type` guidance, i'd be OK w/ the following change to your added sentence...

"The `rel` values MAY contain the `type` property with a value of `application/prs.hal-forms+json`...

note the use of MAY (RFC2119). 

this is backward compatible to any exsiting releases and also allows for future changes that might contain some other `type` value(s).

sound ok?

**Comment by pmoule** [comment]
> Can you explain a bit more why you think the change in text for the "if there is only" -> "for exactly..." is important?

Sure. If there is only one element, then this one MUST have a key named "default". This is clear for me. 
In case of multiple elements, shouldn't there be exactly one element named "default"? Otherwise I do not understand, why  a pre-defined value "default" is required at all.

**Comment by pmoule** [comment]
> for the `rel` and `type` guidance, i'd be OK w/ the following change to your added sentence...
> 
> "The `rel` values MAY contain the `type` property with a value of `application/prs.hal-forms+json`...
> 
> note the use of MAY (RFC2119).
> 
> this is backward compatible to any exsiting releases and also allows for future changes that might contain some other `type` value(s).
> 
> sound ok?

I agree, ok!

**Review by mamund — COMMENTED** [review]
@pmoule 

OK, "exactly one" makes sense to me now. thanks for clarification

and, once the small change (MAY) is committed, we can merge this in.
In case of multiple elements, shouldn't there be exactly one element named "default"? Otherwise I do not understand, why a pre-defined value "default" is required at all.


thanks for your help in improving the spec.

-- @mamund

**Review by mamund — APPROVED** [review]

**Pull request merged**
