### PR TITLE
Proposal for nested data in request bodies

### PR DESCRIPTION
**Pull request by dschulten**
As discussed on [gitter](https://gitter.im/mamund/hal-forms): introduced recursive `properties` element and described processing model

### CODE REVIEW

**Comment by mattbishop** [comment]
@mamund this PR addresses multi-values nicely. I'd like to add "suggest" to this.

**Comment by mattbishop** [comment]
@dschulten would you consider splitting this into two PRs? one for `multi` and one for nested properties? That would make it easier to discuss and digest.

**Comment by randallsquared** [comment]
@dschulten What's the advantage of introducing both bracket notation and dot-separated notation?  The bracket notation would seem to be sufficient, and trades a single extra character for dropping a syntactic rule.

**Comment by gregturn** [comment]
I would favor keeping things simple and simply supporting dot-separated notation to signal subproperties.

**Comment by mamund** [comment]
Agreed.

**Comment by ingogriebsch** [comment]
> I would favor keeping things simple and simply supporting dot-separated notation to signal subproperties.

But how could one then describe that the request body need to contain a 'collection' of resources?

**Comment by mamund** [comment]
@ingogriebsch 

first, can you show an example of what you are talking about and, second, can you show how other formats do what you are asking? (Siren, Cj, HTML, UBER, etc.).

**Pull request closed without merging**
